subject

body
---
Description: add prefix -thor_kernel to the kernel version

Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

diff -up Makefile.orig Makefile
--- Makefile.orig	2021-10-31 20:53:10.000000000 +0000
+++ Makefile	2021-12-11 11:38:00.990997108 +0000
@@ -2,7 +2,7 @@
 VERSION = 5
 PATCHLEVEL = 15
 SUBLEVEL = 0
-EXTRAVERSION =
+EXTRAVERSION = -thor_kernel
 NAME = Trick or Treat
 
 # *DOCUMENTATION*
